ALTER TABLE users ADD COLUMN IF NOT EXISTS district_id INTEGER REFERENCES districts(id) ON DELETE SET NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS mandal_id INTEGER REFERENCES mandals(id) ON DELETE SET NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(255);
